# Dependencies
markdown:         kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      css_class: highlight highlight-numbered
      line_numbers: true
      start_line: 1

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Random kit
tagline:          'eh'
description:      'Random blog for random people'
url:              http://jtanx.github.io
baseurl:          /

author:
  name:           'Jeremy Tan'
  url:            https://github.com/jtanx

gems:             [jekyll-paginate,jekyll-gist,jemoji]
paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jtanx/jtanx.github.io
